### ISSUE TITLE
RL02 Terminator - is it necessary?

### ISSUE THREAD

**Issue by AaronJackson** [ChrisPVille/RL02#7]
Hi Chris,
I saw the video about this project on Hackaday and it didn't look like you had a terminator attached. Is one actually needed? I've been trying to get an RL02 drive to work with my 11/73 but not having much luck. Thanks and great job with this project.

**Comment by ChrisPVille** [comment]
The cable run between my controller card and the drive was around 15cm, under any length where I needed to worry about transmission line effects.  Like the DEC RL11, my controller card has termination resistors on it, which should help quell reflections somewhat.

The system clock is a leisurely 4.1Mhz although the write MFM signal should probably be modeled as ~100Mhz because of the tiny phase shifts caused by write pre-compensation.  Still, at 100Mhz the drive will probably work sans terminator read/write with cable lengths in the low 10s of cm and read-only out over a meter.  As with all things RF, YMMV.

If you find you really need a terminator and can't find an official one (it took me two years to find one), you can build a PCB with the appropriate value termination resistors and connect the internal ribbon cable to it as I believe @NF6X did for his RL-02 interface project [here](https://github.com/NF6X/RL02-USB/tree/master/pcbs/RL02-USB-terminator).

**Comment by AaronJackson** [comment]
Thanks Chris. That's very useful information. I had tried building a terminator but I am beginning to think I'm either very bad at geometry or there is an issue with the drive.
